function(cxxhttp_setup_target target)
  macro(define_missing_options)
    foreach(option IN ITEMS CXXHTTP_INTEGRATE_CURLPP CXXHTTP_INTEGRATE_HTTP_STATUS_CODE CXXHTTP_INTEGRATE_CA_CERTIFICATE_BUNDLE)
      if(NOT DEFINED ${option})
        set(${option} ON)
      endif()
    endforeach()
  endmacro()

  function(setup_fetch_github_content)
    include(FetchContent)
    FetchContent_Declare(fetch_github_content GIT_REPOSITORY https://github.com/CesarBerriot/fetch_github_content.git GIT_TAG 1.0.0)
    FetchContent_MakeAvailable(fetch_github_content)
    include(${fetch_github_content_SOURCE_DIR}/fetch_github_content.cmake)
  endfunction()

  function(setup_curlpp)
    function(setup_curl)
      macro(setup_mbedtls)
        block(PROPAGATE mbedtls_SOURCE_DIR)
          cmake_policy(PUSH)
          cmake_policy(SET CMP0077 NEW)
          set(ENABLE_TESTING OFF)
          set(ENABLE_PROGRAMS OFF)
          set(MBEDTLS_TARGET_PREFIX mbedtls_)
          fetch_github_content(mbedtls Mbed-TLS v3.6.3)
          cmake_policy(POP)
          if(MINGW)
            # see https://github.com/Mbed-TLS/mbedtls/issues/10161
            target_compile_options(mbedtls_mbedtls PRIVATE -Wno-format)
          endif()
        endblock()
      endmacro()

      setup_mbedtls()
      set(BUILD_CURL_EXE OFF)
      set(CURL_DISABLE_INSTALL ON)
      set(CURL_ENABLE_EXPORT_TARGET OFF)
      set(BUILD_EXAMPLES OFF)
      set(ENABLE_CURL_MANUAL OFF)
      set(BUILD_LIBCURL_DOCS OFF)
      set(CURL_USE_LIBPSL OFF)
      set(CURL_USE_MBEDTLS ON)
      set(MBEDTLS_INCLUDE_DIR "${mbedtls_SOURCE_DIR}/include")
      set(MBEDTLS_LIBRARY mbedtls_mbedtls)
      set(MBEDX509_LIBRARY mbedtls_mbedx509)
      set(MBEDCRYPTO_LIBRARY mbedtls_mbedcrypto)
      fetch_github_content(curl curl curl-8_13_0)
    endfunction()

    setup_curl()
    fetch_github_content(curlpp CesarBerriot 1.0.2)
    target_link_libraries(${target} PRIVATE curlpp)
  endfunction()

  function(setup_http_status_codes)
    fetch_github_content(http-status-codes-cpp j-ulrich 1.6.2)
    target_include_directories(${target} PRIVATE ${http-status-codes-cpp_SOURCE_DIR})
  endfunction()

  function(setup_ca_certificates)
    macro(fetch_data)
      block(PROPAGATE data)
        macro(download_data)
          block(PROPAGATE path)
            set(path ${CMAKE_CURRENT_BINARY_DIR}/ca_certificates.pem)
            file(DOWNLOAD https://curl.se/ca/cacert.pem ${path} STATUS status)
            list(GET status 0 error_code)
            if(error_code)
              list(GET status 1 error_description)
              message(FATAL_ERROR "Failed to download the latest cURL CA certificates with error ${error_code} (${error_description}).")
            endif()
          endblock()
        endmacro()

        macro(read_data)
          file(READ ${path} data)
        endmacro()

        download_data()
        read_data()
      endblock()
    endmacro()

    macro(escape_data)
      string(REPLACE "\n" "\\n\"\"" data ${data})
    endmacro()

    macro(generate_header)
      block(PROPAGATE header_path)
        set(header_path ${CMAKE_CURRENT_BINARY_DIR}/ca_certificates.hpp)
        file(WRITE ${header_path} "\
              #include <curl/curl.h>
              static curl_blob ca_certificates = { (void*)\"${data}\", sizeof(\"${data}\") - 1 };
            ")
      endblock()
    endmacro()

    function(add_forced_include)
      set(forced_include_option -include)
      if(MSVC)
        set(forced_include_option /FI)
      endif()
      target_compile_options(${target} PRIVATE ${forced_include_option} ${header_path})
    endfunction()

    fetch_data()
    escape_data()
    generate_header()
    add_forced_include()
  endfunction()

  define_missing_options()
  setup_fetch_github_content()

  if(CXXHTTP_INTEGRATE_CURLPP)
    setup_curlpp()
  endif()

  if(CXXHTTP_INTEGRATE_HTTP_STATUS_CODE)
    setup_http_status_codes()
  endif()

  if(CXXHTTP_INTEGRATE_CA_CERTIFICATE_BUNDLE)
    setup_ca_certificates()
  endif()
endfunction()